// Code generated by hertz generator.

package index

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.sophist.static_analysis/biz/handler"
	"github.sophist.static_analysis/biz/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	index "github.sophist.static_analysis/biz/model/index"
)

// PingServer .
// @router /ping [GET]
func PingServer(ctx context.Context, c *app.RequestContext) {
	var err error
	var req index.PingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	result, err := service.Ping(ctx, req)
	if err != nil {
		hlog.CtxWarnf(ctx, "Ping err Z%v", err)
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(index.PingResp)
	resp.Base = handler.SuccessBase()
	resp.Data = result
	c.JSON(consts.StatusOK, resp)
}
