// Code generated by hertz generator.

package index

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pingserverMw() []app.HandlerFunc {
	// your code...
	return nil
}
